swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:3000
# basePath prefixes all resource paths
basePath: /api
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /dataset/all:
    x-swagger-router-controller: dataset
    get:
      description: Returns all datasets
      operationId: getDatasets
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/DataSets"
  /dataset/united:
    x-swagger-router-controller: dataset
    get:
      description: Returns all datasets
      operationId: getUnitedDataset
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/Dataset"
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        200:
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /about:
    x-swagger-router-controller: hello_world
    get:
      description: Returns information about project
      operationId: about
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/AboutResponse"
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  AboutResponse:
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  DataSets:
    properties:
      datasets:
        type: array
        items:
          type: string
  Dataset:
    properties:
      fields:
        type: array
        items:
          properties:
            id:
              type: string
            type:
              type: string
      records:
        type: array
        items:
          properties:
            District:
              type: string
            Code:
              type: string
            Plan:
              type: string
            Fact:
              type: string
            fond:
              type: string
