swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:3000
# basePath prefixes all resource paths
basePath: /api
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /dataset/all:
    x-swagger-router-controller: dataset
    get:
      description: Returns all datasets
      operationId: getDatasets
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/DataSets"
  /dataset/united:
    x-swagger-router-controller: dataset
    get:
      description: Returns all datasets
      operationId: getUnitedDataset
      parameters:
        - name: id
          description: Dataset id
          in: query
          type: integer
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/Dataset"
  /about:
    x-swagger-router-controller: hello_world
    get:
      description: Returns information about project
      operationId: about
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/AboutResponse"
# complex objects have schema definitions
definitions:
  AboutResponse:
    properties:
      message:
        type: string
  DataSets:
    properties:
      datasets:
        type: array
        items:
          type: string
  Dataset:
    properties:
      fields:
        type: array
        items:
          properties:
            id:
              type: string
            type:
              type: string
      records:
        type: array
        items:
          properties:
            District:
              type: string
            Code:
              type: string
            Plan:
              type: string
            Fact:
              type: string
            fond:
              type: string
